parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - plugin:@typescript-eslint/recommended
overrides:
  - files: src/**/__tests__/**/*.spec.ts
    env:
      jest/global: true
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
